In [1]:
import tensorflow as tf

In [3]:
X = tf.random.normal((10000, 20))
X.shape

TensorShape([10000, 20])

In [4]:
y = tf.random.normal((10000, ))
y.shape

TensorShape([10000])

In [7]:
tf.data?

Type:        module
String form: <module 'tensorflow._api.v2.data' from '/Users/baraa/Library/Caches/pypoetry/virtualenvs/transfor <...> rst-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/_api/v2/data/__init__.py'>
File:        ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/_api/v2/data/__init__.py
Docstring:   Public API for tf._api.v2.data namespace

In [8]:
dataset = tf.data.Dataset.from_tensor_slices((X, y))

dataset = (
    dataset
    .shuffle(10000)
    .batch(64)
    .prefetch(tf.data.AUTOTUNE)
)

In [11]:
tf.keras.losses.CategoricalCrossentropy?

Init signature:
tf.keras.losses.CategoricalCrossentropy(
    from_logits=False,
    label_smoothing=0.0,
    axis=-1,
    reduction='sum_over_batch_size',
    name='categorical_crossentropy',
    dtype=None,
)
Docstring:     
Computes the crossentropy loss between the labels and predictions.

Use this crossentropy loss function when there are two or more label
classes. We expect labels to be provided in a `one_hot` representation. If
you want to provide labels as integers, please use
`SparseCategoricalCrossentropy` loss. There should be `num_classes` floating
point values per feature, i.e., the shape of both `y_pred` and `y_true` are
`[batch_size, num_classes]`.

Args:
    from_logits: Whether `y_pred` is expected to be a logits tensor. By
        default, we assume that `y_pred` encodes a probability distribution.
    label_smoothing: Float in [0, 1]. When > 0, label values are smoothed,
        meaning the confidence on label values are relaxed. For example, if
        `0.1`, use `0.

In [12]:
tf.keras.layers.Dense?

Init signature:
tf.keras.layers.Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    lora_rank=None,
    lora_alpha=None,
    quantization_config=None,
    **kwargs,
)
Docstring:     
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). When this layer is
followed by a `BatchNormalization` layer, it is recommended to set
`use_bias=False` as `BatchNormalization` has its own bias term.

Note: If the input to the layer has a rank greater than 2, `Dense`
computes

In [14]:
model = tf.keras.Sequential([tf.keras.Input((12,)),
                             tf.keras.layers.Dense(32, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(16, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(1),
                            ])

    

In [15]:
tf.keras.losses.BinaryCrossentropy?

Init signature:
tf.keras.losses.BinaryCrossentropy(
    from_logits=False,
    label_smoothing=0.0,
    axis=-1,
    reduction='sum_over_batch_size',
    name='binary_crossentropy',
    dtype=None,
)
Docstring:     
Computes the cross-entropy loss between true labels and predicted labels.

Use this cross-entropy loss for binary (0 or 1) classification applications.
The loss function requires the following inputs:

- `y_true` (true label): This is either 0 or 1.
- `y_pred` (predicted value): This is the model's prediction, i.e, a single
    floating-point value which either represents a
    [logit](https://en.wikipedia.org/wiki/Logit), (i.e, value in [-inf, inf]
    when `from_logits=True`) or a probability (i.e, value in [0., 1.] when
    `from_logits=False`).

Args:
    from_logits: Whether to interpret `y_pred` as a tensor of
        [logit](https://en.wikipedia.org/wiki/Logit) values. By default, we
        assume that `y_pred` is probabilities (i.e., values in [0, 1]).
    label_sm

In [16]:
tf.keras.optimizers.Adam?

Init signature:
tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    weight_decay=None,
    clipnorm=None,
    clipvalue=None,
    global_clipnorm=None,
    use_ema=False,
    ema_momentum=0.99,
    ema_overwrite_frequency=None,
    loss_scale_factor=None,
    gradient_accumulation_steps=None,
    name=None,
    **kwargs,
)
Docstring:     
Optimizer that implements the Adam algorithm.

Adam optimization is a stochastic gradient descent method that is based on
adaptive estimation of first-order and second-order moments.

According to
[Kingma et al., 2014](http://arxiv.org/abs/1412.6980),
the method is "*computationally
efficient, has little memory requirement, invariant to diagonal rescaling of
gradients, and is well suited for problems that are large in terms of
data/parameters*".

Args:
    learning_rate: A float, a
        `keras.optimizers.schedules.LearningRateSchedule` instance, or
        a callable that ta

In [18]:
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True)
optim = tf.keras.optimizers.Adam(learning_rate=1e-3)

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(grads, model.trainable_variables))

loss_metric.update_state(loss)

In [20]:
loss_fn?


Signature:   loss_fn(y_true, y_pred, sample_weight=None)
Type:        BinaryCrossentropy
String form: <LossFunctionWrapper(<function binary_crossentropy at 0x117977100>, kwargs={'from_logits': True, 'label_smoothing': 0.0, 'axis': -1})>
File:        ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/keras/src/losses/losses.py
Docstring:  
Computes the cross-entropy loss between true labels and predicted labels.

Use this cross-entropy loss for binary (0 or 1) classification applications.
The loss function requires the following inputs:

- `y_true` (true label): This is either 0 or 1.
- `y_pred` (predicted value): This is the model's prediction, i.e, a single
    floating-point value which either represents a
    [logit](https://en.wikipedia.org/wiki/Logit), (i.e, value in [-inf, inf]
    when `from_logits=True`) or a probability (i.e, value in [0., 1.] when
    `from_logits=False`).

Args:
    from_logits: Whether to in

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(grads, model.trainable_variables))

loss_metric.update_state(loss)

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optim.apply_gradients(zip(grads, model.trainable_variables))

loss

In [21]:
tf.data.Dataset?

Init signature: tf.data.Dataset(variant_tensor)
Docstring:     
Represents a potentially large set of elements.

The `tf.data.Dataset` API supports writing descriptive and efficient input
pipelines. `Dataset` usage follows a common pattern:

1. Create a source dataset from your input data.
2. Apply dataset transformations to preprocess the data.
3. Iterate over the dataset and process the elements.

Iteration happens in a streaming fashion, so the full dataset does not need to
fit into memory.

Source Datasets:

The simplest way to create a dataset is to create it from a python `list`:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> for element in dataset:
...   print(element)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)

To process lines from files, use `tf.data.TextLineDataset`:

>>> dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])

To process records written in the `TFRecord` format, use `TF

In [90]:
x = tf.random.normal((64, 20))
W = tf.random.normal((20, 32))
b = tf.random.normal((32,))

y = tf.matmul(x, W) + b

In [26]:
x[0,0].numpy()

np.float32(-1.6457713)

In [109]:
model = tf.keras.Sequential([tf.keras.Input((20,)),
                             tf.keras.layers.Dense(64, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(1),
                            ])
                             

In [110]:
loss_fun = tf.keras.losses.BinaryCrossentropy(from_logits=True)

In [111]:
x.shape

TensorShape([20, 10])

In [114]:
pred = model(tf.transpose(x))
pred.shape

TensorShape([10, 1])

In [92]:
probs = tf.sigmoid(pred)

In [93]:
loss = loss_fn(true, probs)

In [94]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.48365503549575806>

In [44]:
tf.data.Dataset?

Init signature: tf.data.Dataset(variant_tensor)
Docstring:     
Represents a potentially large set of elements.

The `tf.data.Dataset` API supports writing descriptive and efficient input
pipelines. `Dataset` usage follows a common pattern:

1. Create a source dataset from your input data.
2. Apply dataset transformations to preprocess the data.
3. Iterate over the dataset and process the elements.

Iteration happens in a streaming fashion, so the full dataset does not need to
fit into memory.

Source Datasets:

The simplest way to create a dataset is to create it from a python `list`:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> for element in dataset:
...   print(element)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)

To process lines from files, use `tf.data.TextLineDataset`:

>>> dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])

To process records written in the `TFRecord` format, use `TF

In [45]:
import numpy as np

In [85]:
X_train_np = np.random.randn(20, 10)
y_train_np = np.random.randint(0, 2, 20)

In [50]:
tf.data.Dataset?

Init signature: tf.data.Dataset(variant_tensor)
Docstring:     
Represents a potentially large set of elements.

The `tf.data.Dataset` API supports writing descriptive and efficient input
pipelines. `Dataset` usage follows a common pattern:

1. Create a source dataset from your input data.
2. Apply dataset transformations to preprocess the data.
3. Iterate over the dataset and process the elements.

Iteration happens in a streaming fashion, so the full dataset does not need to
fit into memory.

Source Datasets:

The simplest way to create a dataset is to create it from a python `list`:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> for element in dataset:
...   print(element)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)

To process lines from files, use `tf.data.TextLineDataset`:

>>> dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])

To process records written in the `TFRecord` format, use `TF

In [86]:
train_ds = (
    tf.data.Dataset
    .from_tensor_slices((X_train_np, y_train_np))
    #.batch(64)
    .shuffle(5000)
    .batch(64)
    .prefetch(tf.data.AUTOTUNE)
)

In [104]:
for x, y in train_ds:
    print(x.shape)
    print(y.shape)
    break

(20, 10)
(20,)


In [67]:
len(train_ds)

157

In [68]:
157 * 64

10048

In [59]:
len(x)

64

In [70]:
x[0]

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([ 2.21636488, -0.21331002,  1.06265208,  0.3880169 , -0.2543586 ,
        1.42131514,  0.87254039, -0.23810739,  0.11892428,  0.16837715])>

In [71]:
for x, y in train_ds:
    print(x[0])
    

tf.Tensor(
[-0.43342139 -0.87267128 -1.12944645  1.46129167 -1.82480735  0.62231112
 -0.72851951  0.81217538 -1.10540682  0.81985678], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.08901353  0.01574402 -0.44578584  2.3205371   1.47306466 -0.58716013
  0.26780295  0.26443316  0.27008965 -1.24627488], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.29739471 -0.11964834 -0.45570712 -0.03752417  0.24645751  0.4751765
 -0.0154233  -0.72893509 -0.27170226 -0.1713642 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.34129677  0.26467385  0.38638191 -0.72218305  1.14053148 -0.47868774
 -0.84608171  1.67049453 -1.05600865 -0.29564646], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.15293037  2.58077391  1.03771345  1.20395452 -0.28739784 -0.17711241
 -0.39749019  0.0259135   0.94861691 -0.59672827], shape=(10,), dtype=float64)
tf.Tensor(
[-0.41165814 -0.89980667 -1.77447904 -0.35259124 -0.13515269  1.27480039
 -0.85381739 -0.75362219  1.57992603  1.56499738], shape=(10,), dtype=float64)
tf.Tensor(
[-0.81210409

In [72]:
x.shape

TensorShape([64, 10])

In [74]:
z = tf.reshape(x, (640, -1))

In [82]:
model.train_function

In [105]:
y.shape

TensorShape([20])

In [116]:
x = tf.transpose(x)

In [120]:
y = tf.random.normal((10,1))
y.shape

TensorShape([10, 1])

In [121]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)
    grads = tape.gradient(loss, model.trainable_variables)

In [96]:
model

<Sequential name=sequential_2, built=True>

In [122]:
grads

[<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
 array([[ 0.02572737,  0.07310952,  0.03541078, ...,  0.08403654,
          0.02415946, -0.05523389],
        [ 0.02454175, -0.11924741,  0.05034967, ...,  0.01178224,
         -0.12622604, -0.01152351],
        [ 0.01217393, -0.1114243 ,  0.01451463, ..., -0.07921324,
         -0.18295002, -0.05697665],
        ...,
        [ 0.01042527,  0.03907387, -0.01292396, ..., -0.00498579,
          0.062736  ,  0.01116171],
        [-0.01912504,  0.00699851, -0.01368154, ..., -0.02055784,
          0.02397827, -0.01025016],
        [-0.0376459 ,  0.01122632, -0.01664925, ...,  0.01242814,
          0.04888831,  0.00205421]], shape=(20, 64), dtype=float32)>,
 <tf.Tensor: shape=(64,), dtype=float32, numpy=
 array([ 1.20718069e-02, -1.34245336e-01,  5.91536090e-02, -6.62488211e-03,
         1.31622851e-02, -3.00574973e-02, -8.70307349e-03,  4.86528128e-02,
         4.50487249e-03,  2.90465429e-02,  2.98116989e-02,  3.54481419e-03,
         3.219

In [123]:
# 1. Global gradient norm
global_norm = tf.linalg.global_norm(grads)

In [125]:
# 2. Clip to global norm 1.0
clipped_grads, z = tf.clip_by_global_norm(grads, 1.0)

In [128]:
clipped_grads

[<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
 array([[ 0.00825948,  0.02347098,  0.01136823, ...,  0.02697898,
          0.00775612, -0.01773221],
        [ 0.00787885, -0.03828302,  0.01616419, ...,  0.00378256,
         -0.04052344, -0.00369949],
        [ 0.0039083 , -0.03577151,  0.00465976, ..., -0.02543051,
         -0.05873403, -0.01829171],
        ...,
        [ 0.00334691,  0.01254422, -0.00414909, ..., -0.00160063,
          0.02014068,  0.00358334],
        [-0.00613987,  0.00224679, -0.0043923 , ..., -0.00659986,
          0.00769795, -0.0032907 ],
        [-0.01208579,  0.00360408, -0.00534505, ...,  0.00398991,
          0.01569504,  0.00065948]], shape=(20, 64), dtype=float32)>,
 <tf.Tensor: shape=(64,), dtype=float32, numpy=
 array([ 3.8755164e-03, -4.3097939e-02,  1.8990593e-02, -2.1268432e-03,
         4.2256019e-03, -9.6496176e-03, -2.7940229e-03,  1.5619433e-02,
         1.4462381e-03,  9.3250629e-03,  9.5707066e-03,  1.1380223e-03,
         1.0334495e-02,  8

In [136]:

grads[0].shape

TensorShape([20, 64])

In [135]:
len(grads)

4

In [138]:
X_train_np.shape, y_train_np.shape

((20, 10), (20,))

In [140]:
train_ds = tf.data.Dataset.from_tensor_slices((X_train_np, y_train_np)).shuffle(5000).batch(64).prefetch(tf.data.AUTOTUNE)

In [141]:
len(train_ds)

1

In [143]:
import pandas as pd

In [144]:
df = pd.DataFrame(columns = ['age', 'churn'])

In [145]:
df['age'] = np.arange(30, 45)

In [146]:
df['churn'] = np.random.randint(0, 2, 15)

In [148]:
X = df.drop(columns=["churn"])
y = df["churn"]

In [155]:
from sklearn.model_selection import train_test_split

In [156]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, train_size=0.7, random_state=42, shuffle=True, stratify=y)



In [158]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, shuffle=True, stratify=y_temp)



In [167]:
X_train.loc[0, 'age'] = np.nan

In [168]:
# Using only X_train, write code to:

# compute median age
# add age_missing
# fill missing age
# fill missing country with "Unknown"

median_age = X_train['age'].median()
X_train['age_missing'] = X_train['age'].fillna(0).astype(bool)
X_train['age'].fillna(median_age, inplace=True)
X_train['country'].fillna('Unknown')

In [169]:
X_train

,age,age_missing
2,32.0,True
1,31.0,True
6,36.0,True
9,39.0,True
10,40.0,True
13,43.0,True
0,NaN,False
12,42.0,True
4,34.0,True
8,38.0,True


In [171]:
from sklearn.preprocessing import StandardScaler

In [172]:
scaler = StandardScaler()

In [179]:
X_train['age'] = X_train['age'].fillna(median_age)

In [180]:
scaler.fit_transform(X_train[['age']])

array([[-1.38659861],
       [-1.64822099],
       [-0.34010909],
       [ 0.44475805],
       [ 0.70638043],
       [ 1.49124757],
       [ 0.18313567],
       [ 1.22962519],
       [-0.86335385],
       [ 0.18313567]])

In [181]:
scaler.transform(X_val[['age']])

array([[-1.12497623],
       [ 0.96800281]])

In [182]:
from sklearn.preprocessing import OneHotEncoder

In [183]:
OneHotEncoder?

Init signature:
OneHotEncoder(
    *,
    categories='auto',
    drop=None,
    sparse_output=True,
    dtype=<class 'numpy.float64'>,
    handle_unknown='error',
    min_frequency=None,
    max_categories=None,
    feature_name_combiner='concat',
)
Docstring:     
Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
encoding scheme. This creates a binary column for each category and
returns a sparse matrix or dense array (depending on the ``sparse_output``
parameter).

By default, the encoder derives the categories based on the unique values
in each feature. Alternatively, you can also specify the `categories`
manually.

This encoding is needed for feeding categorical data to many scikit-learn
estimators, notably linear models and SVMs with the standard kernels.

Note: a o

In [188]:
countries = ['France', 'Morocco', 'UAE']
X_train['country'] = np.random.choice(countries, len(X_train))

In [189]:
X_val['country'] = np.random.choice(countries, len(X_val))

In [192]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit_transform(X_train[['country']])
enc.fit_transform(X_val[['country']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 1)>

In [193]:
X_train#['country']

,age,age_missing,country
2,32.0,True,UAE
1,31.0,True,UAE
6,36.0,True,France
9,39.0,True,France
10,40.0,True,Morocco
13,43.0,True,UAE
0,38.0,False,France
12,42.0,True,Morocco
4,34.0,True,France
8,38.0,True,France


In [194]:
X_val

,age,country
3,33,UAE
11,41,UAE


In [195]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')

X_train_country = enc.fit_transform(X_train[['country']])
X_val_country = enc.transform(X_val[['country']])

In [201]:
type(X_val_country)

scipy.sparse._csr.csr_matrix

In [202]:
from scipy.sparse import hstack

X_train_country = enc.fit_transform(X_train[['country']])
X_val_country = enc.transform(X_val[['country']])

X_train_num = X_train[['age', ]].values
X_val_num = X_val[['age']].values

X_train_final = hstack([X_train_num, X_train_country])
X_val_final = hstack([X_val_num, X_val_country])

In [203]:
X_train_final

<COOrdinate sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 4)>

In [204]:
print(X_train_final.toarray())

[[32.  0.  0.  1.]
 [31.  0.  0.  1.]
 [36.  1.  0.  0.]
 [39.  1.  0.  0.]
 [40.  0.  1.  0.]
 [43.  0.  0.  1.]
 [38.  1.  0.  0.]
 [42.  0.  1.  0.]
 [34.  1.  0.  0.]
 [38.  1.  0.  0.]]


In [205]:
print(X_train_final)

<COOrdinate sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 4)>
  Coords	Values
  (0, 0)	32.0
  (1, 0)	31.0
  (2, 0)	36.0
  (3, 0)	39.0
  (4, 0)	40.0
  (5, 0)	43.0
  (6, 0)	38.0
  (7, 0)	42.0
  (8, 0)	34.0
  (9, 0)	38.0
  (0, 3)	1.0
  (1, 3)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 2)	1.0
  (5, 3)	1.0
  (6, 1)	1.0
  (7, 2)	1.0
  (8, 1)	1.0
  (9, 1)	1.0


In [206]:
X_train_np = X_train_final.toarray()
type(X_train_final.toarray())

numpy.ndarray

In [209]:
y_train_np = y_train.values
type(y_train.values)

numpy.ndarray

In [210]:
train_ds = tf.data.Dataset.from_tensor_slices((X_train_np, y_train_np)).shuffle(5000).batch(64).prefetch(tf.data.AUTOTUNE)

In [216]:
# Block 4 retest — Question 8

# Build a Keras binary classifier with:

# input dimension 12
# hidden layers 32 and 16
# ReLU
# dropout 0.2
# one raw output logit

model = tf.keras.Sequential([tf.keras.Input((4,)),
                             tf.keras.layers.Dense(32, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(16, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(1),
                            ])
                             
                             

In [217]:
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True)
optim = tf.keras.optimizers.Adam(learning_rate=1e-3)

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(grads, model.trainable_variables))

loss_metric.update_state(loss)

In [215]:
x.shape

TensorShape([10, 4])

In [218]:
loss_metric = tf.keras.metrics.Mean(name="loss")
for x, y in train_ds:
    with tf.GradientTape() as tape:
        pred = model(x, training=True)
        loss = loss_fn(y, pred)

    grads = tape.gradient(loss, model.trainable_variables)
    optim.apply_gradients(zip(grads, model.trainable_variables))

    loss_metric.update_state(loss)
print("loss:", loss_metric.result().numpy())

loss: 5.4672394


In [219]:
pred.shape

TensorShape([10, 1])

In [221]:
probs = tf.sigmoid(pred)

In [222]:
probs

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.9963967 ],
       [0.9999996 ],
       [0.9994534 ],
       [0.9990057 ],
       [0.9999999 ],
       [0.99997926],
       [0.75744855],
       [0.9993508 ],
       [1.        ],
       [0.9999079 ]], dtype=float32)>

In [225]:

probs = tf.sigmoid(pred)
class_pred = tf.cast(probs > 0.3, tf.int32)

In [226]:
class_pred

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)>